### PR TITLE
Maybe throw exception if SingleThreadSparkeyReader is used incorrectly

### PR DESCRIPTION
**Pull request by spkrka**

### CODE REVIEW

**Comment by spkrka** [comment]
@danielnorberg Any thoughts on this approach?

**Comment by danielnorberg** [comment]
I think I'd just annotate with @NotThreadSafe and be done with it.

As for this PR, without volatile you might still pay the overhead of the cache line invalidation and get unreliable use detection. Also, I think the JVM might be allowed to freely move or even completely remove the inc/dec. (in which case you won't pay for it but...)

**Comment by danielnorberg** [comment]
Note that the volatile is quite affordable if uncontended, especially if it's used by only one thread.

**Comment by danielnorberg** [comment]
But as always, JMH to verify.

**Comment by spkrka** [comment]
Then maybe I should just add synchronized to all methods - that should also be fairly cheap if it's uncontested.

**Comment by danielnorberg** [comment]
That sounds potentially like an anti pattern.

Regardless, JMH and verify.

**Pull request closed without merging**
